// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBv8cgeejL2bPCOHUwVcqfxNk-Nva9kvU',
    appId: '1:607101626293:web:f17e2f9f3c961e2a291bfc',
    messagingSenderId: '607101626293',
    projectId: 'dataroutine6',
    authDomain: 'dataroutine6.firebaseapp.com',
    storageBucket: 'dataroutine6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuXFVVSqlt221wpoSZe2P8UXJGoC29FTc',
    appId: '1:607101626293:android:3ae784cc0df42780291bfc',
    messagingSenderId: '607101626293',
    projectId: 'dataroutine6',
    storageBucket: 'dataroutine6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHcr9zOSiNkdttzZRDWCfWphEhk3nZi9k',
    appId: '1:607101626293:ios:07e60fabd5aabda0291bfc',
    messagingSenderId: '607101626293',
    projectId: 'dataroutine6',
    storageBucket: 'dataroutine6.firebasestorage.app',
    iosBundleId: 'com.example.dataroutine6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHcr9zOSiNkdttzZRDWCfWphEhk3nZi9k',
    appId: '1:607101626293:ios:07e60fabd5aabda0291bfc',
    messagingSenderId: '607101626293',
    projectId: 'dataroutine6',
    storageBucket: 'dataroutine6.firebasestorage.app',
    iosBundleId: 'com.example.dataroutine6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBv8cgeejL2bPCOHUwVcqfxNk-Nva9kvU',
    appId: '1:607101626293:web:babcc4d5728011b2291bfc',
    messagingSenderId: '607101626293',
    projectId: 'dataroutine6',
    authDomain: 'dataroutine6.firebaseapp.com',
    storageBucket: 'dataroutine6.firebasestorage.app',
  );
}
